In [2]:
import torch

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [7]:
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
torch.tensor([[1,2,3,4],[3,4,1,2],[4,3,2,1]])

tensor([[1, 2, 3, 4],
        [3, 4, 1, 2],
        [4, 3, 2, 1]])

In [11]:
x = torch.tensor([1,2,3,4])
y = torch.tensor([4,3,2,1])
x + y , x - y , x * y , x / y , x ** y

(tensor([5, 5, 5, 5]),
 tensor([-3, -1,  1,  3]),
 tensor([4, 6, 6, 4]),
 tensor([0.2500, 0.6667, 1.5000, 4.0000]),
 tensor([1, 8, 9, 4]))

In [12]:
torch.exp(x)

tensor([ 2.7183,  7.3891, 20.0855, 54.5981])

In [15]:
x = torch.arange(12,dtype = torch.float32).reshape((3,4))
y = torch.tensor([[1,2,3,4],[3,4,1,2],[4,3,2,1]])
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  2.,  3.,  4.],
         [ 3.,  4.,  1.,  2.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  3.,  4.,  1.,  2.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [16]:
x == y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [17]:
x.sum()

tensor(66.)

In [18]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [19]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [24]:
x,x[-1],x[1:3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [25]:
x[1,2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [26]:
x[0:2,:] = 44
x

tensor([[44., 44., 44., 44.],
        [44., 44., 44., 44.],
        [ 8.,  9., 10., 11.]])

In [27]:
before = id(y)
y = y + x
id(y) == before

False

In [28]:
z = torch.zeros_like(y)
print('id(z):',id(z))
z[:] = x + y
print('id(z):',id(z))

id(z): 2370001081104
id(z): 2370001081104


In [29]:
before = id(x)
x += y
id(x) == before

True

In [32]:
a = x.numpy()
b = torch.tensor(a)
type(a),type(b)

(numpy.ndarray, torch.Tensor)

In [31]:
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)